(org-babel-load-file "~/.emacs.d/my-init.org")
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ac-auto-show-menu t)
 '(ac-delay 0.01)
 '(ac-use-fuzzy t)
 '(bm-highlight-style (quote bm-highlight-only-line))
 '(bm-recenter t)
 '(c-basic-offset 4)
 '(comint-buffer-maximum-size 999999)
 '(comint-prompt-read-only nil)
 '(comint-use-prompt-regexp t)
 '(custom-enabled-themes (quote (tango-dark)))
 '(ediff-split-window-function (quote split-window-horizontally))
 '(flex-isearch-auto t)
 '(font-lock-maximum-decoration (quote ((c-mode . 2) (compilation-mode . 3) (t . t))))
 '(font-lock-support-mode (quote jit-lock-mode))
 '(global-auto-revert-non-file-buffers t)
 '(helm-buffers-fuzzy-matching t)
 '(ido-default-buffer-method (quote selected-window))
 '(ido-default-file-method (quote selected-window))
 '(ido-enable-flex-matching t)
 '(indent-tabs-mode nil)
 '(ispell-dictionary "english")
 '(large-file-warning-threshold 100000000)
 '(magit-git-executable "git")
 '(mode-line-in-non-selected-windows nil)
 '(org-replace-disputed-keys t)
 '(package-selected-packages
   (quote
    (toml-mode company-math graphviz-dot-mode todotxt flymd markdown-mode auto-complete minimap xkcd web w3m tidy thing-cmds tabbar stripe-buffer string-utils smooth-scroll revive popwin oneonone nyan-mode number-font-lock-mode nlinum move-text mo-git-blame magit linum-relative key-chord jira inf-ruby icicles hydra highlight-indentation highlight-escape-sequences hide-region help-fns+ helm-projectile helm-mode-manager grep-a-lot gnuplot-mode gitignore-mode gitconfig-mode git-timemachine fuzzy framemove focus fit-frame expand-region evil emms edit-server ecb diff-hl csv-mode company command-log-mode centered-cursor-mode button-lock buffer-move bongo bm android-mode aggressive-indent ace-jump-mode ac-etags)))
 '(proced-auto-update-flag t)
 '(proced-auto-update-interval 1)
 '(projectile-git-command
   " git ls-files -zco && git submodule foreach --quiet 'for file in $(git ls-files -zco); do echo -n \"$path/$file\"; done'")
 '(projectile-project-root-files-functions
   (quote
    (projectile-root-top-down-recurring projectile-root-bottom-up projectile-root-top-down)))
 '(smooth-scroll/hscroll-step-size 2)
 '(smooth-scroll/vscroll-step-size 2)
 '(tags-revert-without-query t)
 '(uniquify-buffer-name-style (quote post-forward) nil (uniquify)))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:inherit nil :stipple nil :background "gray6" :foreground "white" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 75 :width normal :foundry "outline" :family "Liberation Mono"))))
 '(bm-face ((t (:background "hot pink" :foreground "Black"))))
 '(bm-fringe-face ((t (:foreground "hot pink"))))
 '(column-marker-1 ((t (:background "red"))))
 '(comint-highlight-prompt ((t (:inherit nil :slant italic :weight bold))))
 '(compilation-info ((t (:inherit success :foreground "violet"))))
 '(compilation-line-number ((t (:inherit font-lock-keyword-face :foreground "light slate blue"))))
 '(cursor ((t (:background "white"))))
 '(diff-file-header ((t (:background "ghost white" :foreground "black" :weight bold))))
 '(diff-hl-change ((t (:background "DarkGoldenrod4" :foreground "yellow"))))
 '(ecb-default-highlight-face ((t (:inherit show-paren-match))))
 '(font-lock-comment-face ((t (:foreground "gray53" :slant oblique))))
 '(font-lock-debug-tag-face ((t (:background "dark green" :foreground "white" :underline t :weight bold))) t)
 '(font-lock-function-name-face ((t (:foreground "violet"))))
 '(font-lock-keyword-face ((t (:foreground "HotPink1"))))
 '(font-lock-preprocessor-face ((t (:foreground "yellow green"))))
 '(font-lock-string-face ((t (:foreground "burlywood3"))))
 '(font-lock-type-face ((t (:foreground "light slate blue"))))
 '(font-lock-variable-name-face ((t (:foreground "light sky blue"))))
 '(font-lock-warning-tag-face ((t (:inherit font-lock-warning-face :background "red" :foreground "white" :underline t :weight bold))) t)
 '(fringe ((t (:background "gray6"))))
 '(header-line ((t (:inherit default :background "gray17" :foreground "gray80" :box nil :weight bold))))
 '(hide-region-after-string-face ((t (:inherit region :background "red" :weight bold))))
 '(hide-region-before-string-face ((t (:inherit region :background "red" :weight bold))))
 '(highlight-indentation-face ((t (:inherit fringe :background "gray13"))))
 '(hl-line ((t (:background "gray20"))))
 '(isearch ((t (:background "purple1" :foreground "#eeeeec"))))
 '(lazy-highlight ((t (:background "purple4"))))
 '(linum ((t (:inherit (shadow default) :background "gray14"))))
 '(magit-item-highlight ((t (:inherit show-paren-match))))
 '(menu ((t (:background "dim gray" :foreground "ghost white" :inverse-video t))))
 '(minibuffer-prompt ((t (:inherit my-header-line-face :foreground "white" :width semi-expanded))))
 '(mode-line ((t (:background "gray16" :foreground "gray69" :weight light))))
 '(mode-line-buffer-id ((t (:foreground "lemon chiffon" :weight bold))))
 '(mode-line-buffer-name-face ((t (:inherit my-header-line-face :background "#978ECD" :foreground "#2c2656" :weight extra-bold :family "Liberation Sans"))) t)
 '(mode-line-buffer-name-inactive-face ((t (:inherit mode-line-buffer-name-face :background "gray16" :foreground "grey80" :box (:line-width 1 :color "grey7")))) t)
 '(mode-line-emphasis ((t (:foreground "red" :weight bold))))
 '(mode-line-inactive ((t (:inherit mode-line))))
 '(mode-line-major-mode-face ((t (:family "Liberation Sans"))) t)
 '(mode-line-notification-face ((t (:inherit my-header-line-face :background "firebrick" :foreground "gray100" :weight extra-bold :family "liberation mono"))) t)
 '(mode-line-notification-inactive-face ((t (:inherit mode-line-notification-face :background "gray22" :box nil))) t)
 '(mode-line-status-face ((t (:background "gray43" :foreground "gray100" :weight normal :family "liberation mono"))) t)
 '(mode-line-status-inactive-face ((t (:inherit mode-line-status-face :foreground "black"))) t)
 '(mode-line-time-face ((t (:weight bold))) t)
 '(mode-line-vc-face ((t (:family "Liberation Sans"))) t)
 '(my-header-line-face ((t (:background "#2c2656" :foreground "white" :box (:line-width 1 :color "#978ECD") :weight bold))) t)
 '(my-header-line-inactive-face ((t (:inherit my-header-line-face :background "grey12" :foreground "gray62" :box (:line-width 1 :color "grey7")))) t)
 '(number-font-lock-face ((t (:inherit font-lock-string-face))))
 '(region ((t (:background "gray30"))))
 '(region-occurrence-highlight-face ((t (:inherit region-occurrence-no-region-highlight-face :underline t))) t)
 '(region-occurrence-no-region-highlight-face ((t (:background "dark slate blue"))) t)
 '(show-paren-match ((t (:background "SlateBlue4"))))
 '(stripe-highlight ((t (:background "gray10")))))
